[package]
name = "ingress-default-backend"
version = "1.2.4"
authors = ["Yang Sheng Han <progamesigner@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
actix-rt = "2.11"
actix-web = "4.12"
env_logger = "0.11"
futures = "0.3"
handlebars = "6.3"
prometheus = "0.14"
serde_json = "1.0"
